### ISSUE TITLE
code/design review 27.09

### ISSUE THREAD

**Issue by lisagjh** [fdnd-agency/fabrique#19]
Jullie [sitemap en datamodel](https://github.com/orgs/fdnd-agency/projects/38/views/1?pane=issue&itemId=81056084) is erg duidelijk! 

Jullie hebben ook een goede [debriefing](https://github.com/orgs/fdnd-agency/projects/38/views/1?pane=issue&itemId=80784119) geschreven

Ik zie tot nu toe in het projectboard alleen dingen die aan iedereen zijn assigned, en nog niet echt een duidelijke taakverdeling. Misschien zijn jullie daar nog niet ver genoeg voor, maar een goede taakverdeling kan zeker helpen met efficienter werken.

Verder vind ik het goed dat jullie duidelijke conventies hebben afgesproken en deze hebben genoteerd.

Ik ben benieuwd naar jullie eind project! succes :D

**Comment by Hadil66** [comment]
Bedankt! We waren inderdaad nog niet zo ver, maar we hebben nu wel een taakverdeling. 

![image](https://github.com/user-attachments/assets/4b7d37d6-2773-4389-ae48-5ad6a3c5f386)
