### ISSUE TITLE
Sitemap / Wireframe / Datamodel

### ISSUE THREAD

**Issue by Hadil66** [fdnd-agency/fabrique#5]

**Comment by Hadil66** [comment]
### Sitemap & Datamodel
![Image](https://github.com/user-attachments/assets/d69c15e5-2355-467b-bd98-f0b03e1376bd)

**Comment by yujing-student** [comment]
de sitemap en datamodel is overzichtelijk jullie weten goed wat er in de database moet komen en hoe de website eruit komt te zien
