### ISSUE TITLE
Filters z-index aanpassen

### ISSUE THREAD

**Issue by RukiyaTossou** [fdnd-agency/fabrique#50]
De filters zijn nog te zien als het dropdown menu open is

![Image](https://github.com/user-attachments/assets/1fd6803c-8868-4e16-8251-6acb19a5f845)

**Comment by Hadil66** [comment]
**Gefixt: [Commit](https://github.com/Hadil66/DRY-Fabrique-Qatar-Museums/commit/e666f34124e06fdccae7c05b0c66ef78969113bd)**

<img src="https://github.com/user-attachments/assets/1a4ef795-7d57-456a-9cb2-a93fb522d44c" width="300px"
